### ISSUE TITLE
Request to return non-integer values

### ISSUE THREAD

**Issue by keble6** [makecode-extensions/BME280#2]
Hello! I would prefer to have the full floating point numbers returned. For example temperature could return 25.50 degC, but your code returns 25 degC, because it uses Math.idiv.
This is useful for looking at weather trends, for example.

I have a comment on the English used on some blocks. Example: "Temperature below than" is not correct. It should be "Temperature lower than"

But a very useful extension! Thank you.

**Comment by shaoziyang** [comment]
When I developed this software, MakeCode didn't support floating-point. I will update it later.

**Comment by keble6** [comment]
Thank you!
Rob

**Comment by fluxion-t** [comment]
Hello, I would like to ask the same as keble6. It seems the update to floating point numbers was never done. Please update all variables to floating point precision.


Thank you

**Comment by shaoziyang** [comment]
@fluxion-t @keble6 Please use folating point number version in https://github.com/makecode-extensions/BME280_2. The original version is still kept to ensure compatibility with older versions of makecode.
